#FROM centos:7.8.2003
FROM nvidia/cuda:11.7.1-devel-centos7

LABEL maintainer="wzkres" \
  description="CentOS 7 CI build worker image with gcc, git, cmake, cppcheck, sonarscanner, cuda, etc for c/c++ projects"
        
RUN yum -y update && yum -y install epel-release && yum -y install centos-release-scl
RUN yum -y install wget devtoolset-8 automake libtool autoconf git
# libva dependencies
RUN yum -y install libdrm-devel
# v4l2 dependencies
RUN yum -y install alsa-lib-devel

#RUN scl enable devtoolset-8 bash
SHELL ["/usr/bin/scl", "enable", "devtoolset-8"]

# Download & Compile CMake
RUN wget -q --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.29.4/cmake-3.29.4.tar.gz && \
  tar zxf cmake-3.29.4.tar.gz && \
  cd cmake-3.29.4 && \
  ./bootstrap -- -DCMAKE_USE_OPENSSL=OFF && \
  make -s -j4 && \
  make install && \
  cd .. && \
  rm -rf cmake-3.29.4 && \
  rm -rf cmake-3.29.4.tar.gz && \
  cmake --version

# Download & Compile NASM
RUN wget -q --no-check-certificate https://www.nasm.us/pub/nasm/releasebuilds/2.15.03/nasm-2.15.03.tar.gz && \
  tar zxf nasm-2.15.03.tar.gz && \
  cd nasm-2.15.03 && \
  ./configure && \
  make -s -j4 && \
  make install && \
  cd .. && \
  rm -rf nasm-2.15.03 && \
  rm -rf nasm-2.15.03.tar.gz

# Download & Compile Cppcheck
RUN wget -q --no-check-certificate https://github.com/danmar/cppcheck/archive/refs/tags/2.7.5.tar.gz && \
  tar zxf 2.7.5.tar.gz && \
  mkdir cppcheck-2.7.5/cmake_build && \
  cd cppcheck-2.7.5/cmake_build && \
  cmake -DCMAKE_BUILD_TYPE=Release ../ && \
  make -s -j4 && \
  make install && \
  cd ../../ && \
  rm -rf cppcheck-2.7.5 && \
  rm -rf 2.7.5.tar.gz
  
# Download & Compile clang-tidy 15.0.6
RUN wget -q --no-check-certificate https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.6/llvm-project-15.0.6.src.tar.xz && \
  tar xf llvm-project-15.0.6.src.tar.xz && \
  mkdir llvm-project-15.0.6.src/cmake_build && \
  cd llvm-project-15.0.6.src/cmake_build && \
  cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;" ../llvm && \
  make -s -j4 install-clang-tidy && \
  cd ../../ && \
  rm -rf llvm-project-15.0.6.src && \
  rm -rf llvm-project-15.0.6.src.tar.xz

# Download SonarScanner CLI
RUN wget -q --no-check-certificate https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip && \
  unzip -q sonar-scanner-cli-4.8.0.2856-linux.zip && \
  rm -rf sonar-scanner-cli-4.8.0.2856-linux.zip

RUN yum clean all

ENV PATH "/usr/local/cuda-11.7/bin:/sonar-scanner-4.8.0.2856-linux/bin${PATH:+:${PATH}}"
ENV LD_LIBRARY_PATH "/usr/local/cuda-11.7/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

ENTRYPOINT ["/usr/bin/scl", "enable", "devtoolset-8", "--"]
CMD ["/usr/bin/scl", "enable", "devtoolset-8", "--", "/bin/bash"]
