#FROM centos:7.8.2003
FROM nvidia/cuda:11.7.1-devel-centos7

LABEL maintainer="wzkres" \
  description="CentOS 7 CI build worker image with gcc, git, cmake, python3, meson, ninja-build, cuda, etc for c/c++ projects"
        
RUN yum -y update && yum -y install epel-release && yum -y install centos-release-scl
RUN yum -y install wget devtoolset-8 automake libtool autoconf git
RUN yum -y install rh-python36 ninja-build patchelf
# libva dependencies
RUN yum -y install libdrm-devel
# v4l2 dependencies
RUN yum -y install alsa-lib-devel
# postgres dependencies
RUN yum -y install bison

# Enable devtoolset-8
RUN echo "source /opt/rh/devtoolset-8/enable" >> /etc/bashrc
RUN echo "source /opt/rh/rh-python36/enable" >> /etc/bashrc
SHELL ["/bin/bash", "--login", "-c"]
RUN gcc --version
RUN python --version
RUN pip3 install meson

# Download & Compile CMake
RUN wget -q --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.29.4/cmake-3.29.4.tar.gz && \
  tar zxf cmake-3.29.4.tar.gz && \
  cd cmake-3.29.4 && \
  ./bootstrap -- -DCMAKE_USE_OPENSSL=OFF && \
  make -s -j4 && \
  make install && \
  cd .. && \
  rm -rf cmake-3.29.4 && \
  rm -rf cmake-3.29.4.tar.gz && \
  cmake --version

# Compile NASM
RUN wget https://www.nasm.us/pub/nasm/releasebuilds/2.15.03/nasm-2.15.03.tar.gz && \
  tar zxvf nasm-2.15.03.tar.gz && \
  cd nasm-2.15.03 && \
  ./configure && \
  make && \
  make install && \
  cd .. && \
  rm -rf nasm-2.15.03 && \
  rm -rf nasm-2.15.03.tar.gz

# ffnvcodec
RUN git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
RUN cd nv-codec-headers && make install && cd ..

RUN yum clean all

ENV PATH "/usr/local/cuda-11.7/bin${PATH:+:${PATH}}"
ENV LD_LIBRARY_PATH "/usr/local/cuda-11.7/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

ENTRYPOINT ["/usr/bin/scl", "enable", "devtoolset-8", "rh-python36", "--"]
CMD ["/usr/bin/scl", "enable", "devtoolset-8", "rh-python36", "--", "/bin/bash"]
