#FROM centos:7.8.2003
FROM nvidia/cuda:11.1-devel-centos7

LABEL maintainer="wzkres" \
        description="CentOS 7 CI build worker image with gcc, git, cmake, cppcheck, sonarscanner etc for c/c++ projects"
        
RUN yum -y update && yum -y install epel-release && yum -y install centos-release-scl
RUN yum -y install wget devtoolset-8 automake libtool autoconf cmake cmake3 git

#RUN scl enable devtoolset-8 bash
SHELL ["/usr/bin/scl", "enable", "devtoolset-8"]

RUN alternatives --install /usr/local/bin/cmake cmake /usr/bin/cmake 10
RUN alternatives --install /usr/local/bin/cmake cmake /usr/bin/cmake3 20

# Download & Compile NASM
RUN wget -q --no-check-certificate https://www.nasm.us/pub/nasm/releasebuilds/2.15.03/nasm-2.15.03.tar.gz && \
  tar zxf nasm-2.15.03.tar.gz && \
  cd nasm-2.15.03 && \
  ./configure && \
  make -s -j4 && \
  make install && \
  cd .. && \
  rm -rf nasm-2.15.03 && \
  rm -rf nasm-2.15.03.tar.gz

# Download & Compile Cppcheck
RUN wget -q --no-check-certificate https://github.com/danmar/cppcheck/archive/2.3.tar.gz && \
  tar zxf 2.3.tar.gz && \
  mkdir cppcheck-2.3/cmake_build && \
  cd cppcheck-2.3/cmake_build && \
  cmake -DCMAKE_BUILD_TYPE=Release ../ && \
  make -s -j4 && \
  make install && \
  cd ../../ && \
  rm -rf cppcheck-2.3 && \
  rm -rf 2.3.tar.gz
  
# Download & Compile clang-tidy 10.0.1
RUN wget -q --no-check-certificate https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/llvm-project-10.0.1.tar.xz && \
  tar xf llvm-project-10.0.1.tar.xz && \
  mkdir llvm-project-10.0.1/cmake_build && \
  cd llvm-project-10.0.1/cmake_build && \
  cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;" ../llvm && \
  make -s -j4 install-clang-tidy && \
  cd ../../ && \
  rm -rf llvm-project-10.0.1 && \
  rm -rf llvm-project-10.0.1.tar.xz

# Download SonarScanner CLI
RUN wget -q --no-check-certificate https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip && \
  unzip -q sonar-scanner-cli-4.6.0.2311-linux.zip && \
  rm -rf sonar-scanner-cli-4.6.0.2311-linux.zip

RUN yum clean all

ENV PATH "$PATH:/sonar-scanner-4.6.0.2311-linux/bin"

ENTRYPOINT ["/usr/bin/scl", "enable", "devtoolset-8", "--"]
CMD ["/usr/bin/scl", "enable", "devtoolset-8", "--", "/bin/bash"]
