#!/bin/bash

set -e

if [ $DOCKER_TAG == "centos-7" ]; then
	docker tag $IMAGE_NAME $DOCKER_REPO:7
    docker push $DOCKER_REPO:7
elif [ $DOCKER_TAG == "latest" ]; then
	for tag in {centos-8,8}; do
    	docker tag $IMAGE_NAME $DOCKER_REPO:${tag}
    	docker push $DOCKER_REPO:${tag}
	done
fi
