name: Docker Image CI

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
#    -
#      name: Build and push Dockerfile-7-python3
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        file: ./Dockerfile-7-python3
#        push: true
#        tags: ${{ secrets.DOCKER_USERNAME }}/centos-ci-gcc:centos-7-python3
    -
      name: Build and push Dockerfile-7
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-7
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/centos-ci-gcc:centos-7
        
